export interface Course {
  id: string
  title: string
  description: string
  instructor: string
  instructorImage: string
  price: number
  originalPrice: number
  rating: number
  reviews: number
  students: number
  image: string
  category: string
  level: "Beginner" | "Intermediate" | "Advanced"
  duration: string
  lessons: number
}

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "The Complete JavaScript Course 2024",
    description: "Learn JavaScript from scratch and become a professional developer",
    instructor: "Jonas Schmedtmann",
    instructorImage: "/instructor-teaching.png",
    price: 14.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviews: 1250000,
    students: 2500000,
    image: "/javascript-course.png",
    category: "Web Development",
    level: "Beginner",
    duration: "69 hours",
    lessons: 302,
  },
  {
    id: "2",
    title: "React - The Complete Guide 2024",
    description: "Master React with hooks, context, and modern patterns",
    instructor: "Maximilian Schwarzmüller",
    instructorImage: "/instructor-teaching.png",
    price: 14.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 850000,
    students: 1800000,
    image: "/react-course.png",
    category: "Web Development",
    level: "Intermediate",
    duration: "48 hours",
    lessons: 385,
  },
  {
    id: "3",
    title: "Python for Data Science and Machine Learning",
    description: "Learn Python, NumPy, Pandas, Scikit-learn, and more",
    instructor: "Jose Portilla",
    instructorImage: "/instructor-teaching.png",
    price: 12.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviews: 620000,
    students: 1200000,
    image: "/python-data-science.png",
    category: "Data Science",
    level: "Intermediate",
    duration: "22 hours",
    lessons: 156,
  },
  {
    id: "4",
    title: "The Web Developer Bootcamp 2024",
    description: "Become a full-stack web developer with HTML, CSS, JavaScript, and more",
    instructor: "Colt Steele",
    instructorImage: "/instructor-teaching.png",
    price: 14.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviews: 950000,
    students: 2100000,
    image: "/web-development-bootcamp.png",
    category: "Web Development",
    level: "Beginner",
    duration: "63 hours",
    lessons: 420,
  },
  {
    id: "5",
    title: "Advanced CSS and Sass",
    description: "Master modern CSS techniques and Sass preprocessing",
    instructor: "Jonas Schmedtmann",
    instructorImage: "/instructor-teaching.png",
    price: 11.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviews: 340000,
    students: 680000,
    image: "/css-sass-course.jpg",
    category: "Web Development",
    level: "Intermediate",
    duration: "28 hours",
    lessons: 224,
  },
  {
    id: "6",
    title: "Node.js, Express, MongoDB & More",
    description: "Build complete backend applications with Node.js and Express",
    instructor: "Andrew Mead",
    instructorImage: "/instructor-teaching.png",
    price: 13.99,
    originalPrice: 89.99,
    rating: 4.7,
    reviews: 520000,
    students: 1100000,
    image: "/nodejs-backend.png",
    category: "Backend Development",
    level: "Intermediate",
    duration: "40 hours",
    lessons: 312,
  },
  {
    id: "7",
    title: "TypeScript Masterclass",
    description: "Learn TypeScript from basics to advanced patterns",
    instructor: "Stephen Grider",
    instructorImage: "/instructor-teaching.png",
    price: 12.99,
    originalPrice: 84.99,
    rating: 4.8,
    reviews: 280000,
    students: 580000,
    image: "/typescript-course.png",
    category: "Web Development",
    level: "Intermediate",
    duration: "35 hours",
    lessons: 268,
  },
  {
    id: "8",
    title: "UI/UX Design Fundamentals",
    description: "Learn design principles, wireframing, and prototyping",
    instructor: "Sarah Chen",
    instructorImage: "/instructor-teaching.png",
    price: 11.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviews: 180000,
    students: 420000,
    image: "/ui-ux-design-concept.png",
    category: "Design",
    level: "Beginner",
    duration: "24 hours",
    lessons: 156,
  },
  {
    id: "9",
    title: "AWS Solutions Architect Associate",
    description: "Prepare for AWS certification with comprehensive training",
    instructor: "Stephane Maarek",
    instructorImage: "/instructor-teaching.png",
    price: 13.99,
    originalPrice: 94.99,
    rating: 4.7,
    reviews: 420000,
    students: 890000,
    image: "/aws-cloud-landscape.png",
    category: "Cloud Computing",
    level: "Advanced",
    duration: "32 hours",
    lessons: 280,
  },
  {
    id: "10",
    title: "Docker & Kubernetes Complete Guide",
    description: "Master containerization and orchestration",
    instructor: "Stephen Grider",
    instructorImage: "/instructor-teaching.png",
    price: 14.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 310000,
    students: 720000,
    image: "/docker-kubernetes.png",
    category: "DevOps",
    level: "Advanced",
    duration: "38 hours",
    lessons: 298,
  },
  {
    id: "11",
    title: "Next.js 14 & React - The Complete Guide",
    description: "Build modern full-stack applications with Next.js",
    instructor: "Maximilian Schwarzmüller",
    instructorImage: "/instructor-teaching.png",
    price: 14.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviews: 180000,
    students: 420000,
    image: "/nextjs-react.jpg",
    category: "Web Development",
    level: "Intermediate",
    duration: "45 hours",
    lessons: 356,
  },
  {
    id: "12",
    title: "Mobile App Development with Flutter",
    description: "Create beautiful cross-platform mobile apps",
    instructor: "Maximilian Schwarzmüller",
    instructorImage: "/instructor-teaching.png",
    price: 12.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviews: 150000,
    students: 380000,
    image: "/flutter-mobile-app.png",
    category: "Mobile Development",
    level: "Beginner",
    duration: "42 hours",
    lessons: 334,
  },
]

export const categories = [
  "All",
  "Web Development",
  "Data Science",
  "Backend Development",
  "Design",
  "Cloud Computing",
  "DevOps",
  "Mobile Development",
]

export const levels = ["All", "Beginner", "Intermediate", "Advanced"]
